travis:
  secure:
    BINSTAR_TOKEN: EJgwjud+EUccJRMSIcglD7r3cn2Q/bL0R6fzPlmm2MGfZ3pGuD2U/exciVNeuyHA+p9BSzwIp7c+dqPhmuXTKY+paH/LDqCXGRv4WgbX+t9I2R/DJye1jq6M2GlkeUYiYZ4GjoKZ/NzcGm884Rqs2bA5sN/GORqmDFGZWtRAZak9KNw2M7AWif1o97++U+i2Vf4KaOgtYkUdJ3u+tEDHqunv2hBeoVua4PvdP6oHsScLwR3KSFppg00fNncjfPMGpmPYVcmjjGDuf6fsiO/mYdG/o5aq3RsnOwHbuMgQ1ipHkCIFlPAc2MA1u8ssvLzICCqzKnrfl1NezMX2tR7CpaAggD6QAjbVkVc7VUxRuOOrpkmtki7IL+/Esd/+fHXUlzvcIaOXBZIzkLPV+P/+/z8x1rVN5fwLzMOuf0f23Yx++xPY+QmbmwDWbgJjO0ZpgmSp5XhMjYqU9zFt3Cf70/jtJ/L8MI5JRgK2FOJonDn8ooSw0Ren24JnDyUQgokLxN0glcPFyhDEZzWpXZ4EsWBO9FTthUwVtqF+juAcZ7ilRg9Cv7zV6eLvvzso5VfLIUUdHyWuuUrHixFOwxWg4xMm+P01Ai6J0otLhW57P7URIzjVtySfqexxIoba/7KM7GImktOoGKeGenva0nG2fSCMjUuAFVEdPQvbndbjnaM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
